name: Access Secrets Workflow

on:
  push:
    branches:
      - main

jobs:
  access-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your steps here to build, test, or deploy your project
      # ...

      - name: Access GitHub Secret
        env:
            OPENAI_API_KEY: ${{ secrets.REACT_APP_OPENAI_API_KEY }}
        run: |
          echo "My secret value: $OPENAI_API_KEY"